baseURL = "https://SchrodingerZhu.github.io/ReuseIR"
languageCode = "en-us"
title = "ReuseIR"
theme = "mlir"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

disablePathToLower = true

[Params]

    # Souce Code repository section
    description = "Reuse Analysis in MLIR and Rust"
    # Update menubar link too.
    github_repository = "https://github.com/SchrodingerZhu/ReuseIR"
    version = ""

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/SchrodingerZhu/ReuseIR/tree/main/reuse-www"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Theme settings section
    # Theme color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = []

# Global menu section
[[menu.main]]
    name = "Releases"
    weight = 30
    url = "https://github.com/SchrodingerZhu/ReuseIR/releases"

[[menu.main]]
    name = "Source"
    weight = 20
    url = "https://github.com/SchrodingerZhu/ReuseIR"

[[menu.main]]
    name = "Dialect"
    parent = "Source"
    weight = 3
    url = "https://github.com/SchrodingerZhu/ReuseIR/tree/main/reuse-mlir"

[[menu.main]]
    name = "Frontend"
    parent = "Source"
    weight = 2
    url = "https://github.com/SchrodingerZhu/ReuseIR/tree/main/reuse-frontend"

[[menu.main]]
    name = "Runtime"
    parent = "Source"
    weight = 1
    url = "https://github.com/SchrodingerZhu/ReuseIR/tree/main/reuse-runtime"

[[menu.main]]
    name = "Issues"
    weight = 10
    url = "https://github.com/SchrodingerZhu/ReuseIR/issues"

[[menu.main]]
    name = "Report issue"
    parent = "Issues"
    weight = 1
    url = "https://github.com/SchrodingerZhu/ReuseIR/issues/new/choose"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
